#use this in ubuntu with freeglut3
run:
	g++ Project.cpp -lGL -lGLU -lglut -o project
	./project
drag:
	 g++ ProjectDrag.cpp -lGL -lGLU -lglut -o project
	./project
#needed for opengl and C++
setup:
	sudo apt-get install freeglut3-dev build-essential binutils-gold
clean:
	rm project
